jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: {{ env_var('DBT_PASSWORD')}}
      port: 5432
      dbname: database # or database instead of dbname
      schema: public
      threads: 4